<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultset [
    <!ELEMENT resultset (resultsetdata) >
    <!ELEMENT resultsetdata (row)* >
    <!ELEMENT row (column)+ >
    <!ELEMENT column (#PCDATA)>
    <!ATTLIST column
        null (true | false) "false"
        name CDATA #IMPLIED
    >
]>
<resultset>
    <row>
        <column name="PID">100</column>
        <column name="LATITUDE">32.499885</column>
        <column name="LONGITUDE">-97.602997</column>
        <column name="NAME">Gusher 1</column>
        <column name="Well_Name">Gusher</column>
        <column name="well_number">1</column>
        <column name="operator">GGX</column>
        <column name="status">Proposed</column>
        <column name="final_td">100.00000</column>
        <column name="spud_date" null="true"></column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">950.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude" null="true"></column>
        <column name="bh_longitude" null="true"></column>
    </row>
    <row>
        <column name="PID">42221311570000</column>
        <column name="LATITUDE">32.48939</column>
        <column name="LONGITUDE">-97.61861</column>
        <column name="NAME">LITTLE HOSS V1H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">V1H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9300.00000</column>
        <column name="spud_date">2006-09-22 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">986.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49612</column>
        <column name="bh_longitude">-97.62191</column>
    </row>
    <row>
        <column name="PID">42221311580000</column>
        <column name="LATITUDE">32.48943</column>
        <column name="LONGITUDE">-97.6186</column>
        <column name="NAME">LITTLE HOSS V2H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">V2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">100.00000</column>
        <column name="spud_date">2006-10-18 00:00:00.000</column>
        <column name="comp_date">2007-02-11 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">986.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49660</column>
        <column name="bh_longitude">-97.62058</column>
    </row>
    <row>
        <column name="PID">42221311580009</column>
        <column name="LATITUDE">32.48943</column>
        <column name="LONGITUDE">-97.6186</column>
        <column name="NAME">LITTLE HOSS V2P</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">V2P</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">6660.00000</column>
        <column name="spud_date">2006-10-18 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">986.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48942</column>
        <column name="bh_longitude">-97.61862</column>
    </row>
    <row>
        <column name="PID">42221311590000</column>
        <column name="LATITUDE">32.48947</column>
        <column name="LONGITUDE">-97.61859</column>
        <column name="NAME">LITTLE HOSS V3H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">V3H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9186.00000</column>
        <column name="spud_date">2006-11-09 00:00:00.000</column>
        <column name="comp_date">2007-02-12 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">986.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49729</column>
        <column name="bh_longitude">-97.61928</column>
    </row>
    <row>
        <column name="PID">42221312450000</column>
        <column name="LATITUDE">32.48025</column>
        <column name="LONGITUDE">-97.61957</column>
        <column name="NAME">LITTLE HOSS P1H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">P1H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">8325.00000</column>
        <column name="spud_date">2007-04-12 00:00:00.000</column>
        <column name="comp_date">2008-05-04 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">949.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48646</column>
        <column name="bh_longitude">-97.62182</column>
    </row>
    <row>
        <column name="PID">42221312460000</column>
        <column name="LATITUDE">32.480169999999994</column>
        <column name="LONGITUDE">-97.61957</column>
        <column name="NAME">LITTLE HOSS P2H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">P2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9600.00000</column>
        <column name="spud_date">2007-05-09 00:00:00.000</column>
        <column name="comp_date">2007-12-27 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">949.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48912</column>
        <column name="bh_longitude">-97.62103</column>
    </row>
    <row>
        <column name="PID">42221312470000</column>
        <column name="LATITUDE">32.48021</column>
        <column name="LONGITUDE">-97.61957</column>
        <column name="NAME">LITTLE HOSS P3H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">P3H</column>
        <column name="operator">erfg</column>
        <column name="status">GAS</column>
        <column name="final_td">8616.00000</column>
        <column name="spud_date">2007-04-26 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">949.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48646</column>
        <column name="bh_longitude">-97.61875</column>
    </row>
    <row>
        <column name="PID">42221313040000</column>
        <column name="LATITUDE">32.51024999999999</column>
        <column name="LONGITUDE">-97.62006</column>
        <column name="NAME">LITTLE HOSS D6H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">D6H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9393.00000</column>
        <column name="spud_date">2007-03-12 00:00:00.000</column>
        <column name="comp_date">2007-05-30 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">988.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.50265</column>
        <column name="bh_longitude">-97.61963</column>
    </row>
    <row>
        <column name="PID">42221313050000</column>
        <column name="LATITUDE">32.51028999999999</column>
        <column name="LONGITUDE">-97.62006</column>
        <column name="NAME">LITTLE HOSS D5H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">D5H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10351.00000</column>
        <column name="spud_date">2007-03-27 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">988.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.50268</column>
        <column name="bh_longitude">-97.61774</column>
    </row>
    <row>
        <column name="PID">42221313770000</column>
        <column name="LATITUDE">32.50885</column>
        <column name="LONGITUDE">-97.63386</column>
        <column name="NAME">LITTLE HOSS A2H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">A2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9601.00000</column>
        <column name="spud_date">2007-05-25 00:00:00.000</column>
        <column name="comp_date">2007-07-13 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1012.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49812</column>
        <column name="bh_longitude">-97.63166</column>
    </row>
    <row>
        <column name="PID">42221313780000</column>
        <column name="LATITUDE">32.50888</column>
        <column name="LONGITUDE">-97.63384</column>
        <column name="NAME">LITTLE HOSS A4H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">A4H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10556.00000</column>
        <column name="spud_date">2007-06-11 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1012.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49812</column>
        <column name="bh_longitude">-97.62829</column>
    </row>
    <row>
        <column name="PID">42221314730000</column>
        <column name="LATITUDE">32.46526</column>
        <column name="LONGITUDE">-97.62051</column>
        <column name="NAME">LITTLE HOSS 7 F2H</column>
        <column name="Well_Name">LITTLE HOSS 7</column>
        <column name="well_number">F2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">11030.00000</column>
        <column name="spud_date">2007-10-17 00:00:00.000</column>
        <column name="comp_date">2007-08-19 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">893.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.45163</column>
        <column name="bh_longitude">-97.61149</column>
    </row>
    <row>
        <column name="PID">42221314740000</column>
        <column name="LATITUDE">32.46526</column>
        <column name="LONGITUDE">-97.62047</column>
        <column name="NAME">LITTLE HOSS 7 F4H</column>
        <column name="Well_Name">LITTLE HOSS 7</column>
        <column name="well_number">F4H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">100.00000</column>
        <column name="spud_date">2007-10-01 00:00:00.000</column>
        <column name="comp_date">2008-10-10 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">893.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.45182</column>
        <column name="bh_longitude">-97.60744</column>
    </row>
    <row>
        <column name="PID">42221316750000</column>
        <column name="LATITUDE">32.510296</column>
        <column name="LONGITUDE">-97.619989</column>
        <column name="NAME">LITTLE HOSS D7H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">D7H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10750.00000</column>
        <column name="spud_date">2008-07-27 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">988.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.51953</column>
        <column name="bh_longitude">-97.62212</column>
    </row>
    <row>
        <column name="PID">42251311140000</column>
        <column name="LATITUDE">32.4601</column>
        <column name="LONGITUDE">-97.57454</column>
        <column name="NAME">LITTLE HOSS J6H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">J6H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9468.00000</column>
        <column name="spud_date">2006-08-18 00:00:00.000</column>
        <column name="comp_date">2006-12-22 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">982.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.45640</column>
        <column name="bh_longitude">-97.57451</column>
    </row>
    <row>
        <column name="PID">42251311140009</column>
        <column name="LATITUDE">32.4601</column>
        <column name="LONGITUDE">-97.57454</column>
        <column name="NAME">LITTLE HOSS J6P</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">J6P</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">7115.00000</column>
        <column name="spud_date">2006-08-18 00:00:00.000</column>
        <column name="comp_date" null="true"></column>
        <column name="lease_name" null="true"></column>
        <column name="elev">982.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.46419</column>
        <column name="bh_longitude">-97.57589</column>
    </row>
    <row>
        <column name="PID">42251311170000</column>
        <column name="LATITUDE">32.4601</column>
        <column name="LONGITUDE">-97.57464</column>
        <column name="NAME">LITTLE HOSS J8H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">J8H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9416.00000</column>
        <column name="spud_date">2006-10-15 00:00:00.000</column>
        <column name="comp_date">2006-12-23 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">982.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.45532</column>
        <column name="bh_longitude">-97.57707</column>
    </row>
    <row>
        <column name="PID">42251311180000</column>
        <column name="LATITUDE">32.4601</column>
        <column name="LONGITUDE">-97.57459000000001</column>
        <column name="NAME">LITTLE HOSS J7H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">J7H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10030.00000</column>
        <column name="spud_date">2006-09-23 00:00:00.000</column>
        <column name="comp_date">2006-12-23 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">982.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.45520</column>
        <column name="bh_longitude">-97.57559</column>
    </row>
    <row>
        <column name="PID">42251312110000</column>
        <column name="LATITUDE">32.45505</column>
        <column name="LONGITUDE">-97.58275000000002</column>
        <column name="NAME">LITTLE HOSS I2H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">I2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9248.00000</column>
        <column name="spud_date">2007-01-13 00:00:00.000</column>
        <column name="comp_date">2007-02-01 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">956.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.46202</column>
        <column name="bh_longitude">-97.58944</column>
    </row>
    <row>
        <column name="PID">42251312120000</column>
        <column name="LATITUDE">32.4551</column>
        <column name="LONGITUDE">-97.58275000000002</column>
        <column name="NAME">LITTLE HOSS I3H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">I3H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9542.00000</column>
        <column name="spud_date">2006-11-19 00:00:00.000</column>
        <column name="comp_date">2007-04-07 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">956.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.46347</column>
        <column name="bh_longitude">-97.58818</column>
    </row>
    <row>
        <column name="PID">42251312130000</column>
        <column name="LATITUDE">32.45514</column>
        <column name="LONGITUDE">-97.58275000000002</column>
        <column name="NAME">LITTLE HOSS I4H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">I4H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9550.00000</column>
        <column name="spud_date">2006-10-25 00:00:00.000</column>
        <column name="comp_date">2006-11-16 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">956.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.46373</column>
        <column name="bh_longitude">-97.58654</column>
    </row>
    <row>
        <column name="PID">42251312720000</column>
        <column name="LATITUDE">32.48951999999999</column>
        <column name="LONGITUDE">-97.58526</column>
        <column name="NAME">LITTLE HOSS Z3H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">Z3H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9772.00000</column>
        <column name="spud_date">2006-11-09 00:00:00.000</column>
        <column name="comp_date">2007-02-19 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1015.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48242</column>
        <column name="bh_longitude">-97.57822</column>
    </row>
    <row>
        <column name="PID">42251312730000</column>
        <column name="LATITUDE">32.48951999999999</column>
        <column name="LONGITUDE">-97.58521</column>
        <column name="NAME">LITTLE HOSS Z2H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">Z2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9927.00000</column>
        <column name="spud_date">2006-11-27 00:00:00.000</column>
        <column name="comp_date">2007-02-19 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1015.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48240</column>
        <column name="bh_longitude">-97.57615</column>
    </row>
    <row>
        <column name="PID">42251312740000</column>
        <column name="LATITUDE">32.48951999999999</column>
        <column name="LONGITUDE">-97.58516</column>
        <column name="NAME">LITTLE HOSS Z1H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">Z1H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10020.00000</column>
        <column name="spud_date">2006-12-15 00:00:00.000</column>
        <column name="comp_date">2007-02-19 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1015.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48256</column>
        <column name="bh_longitude">-97.57427</column>
    </row>
    <row>
        <column name="PID">42251312830000</column>
        <column name="LATITUDE">32.49099</column>
        <column name="LONGITUDE">-97.60329</column>
        <column name="NAME">LITTLE HOSS X2H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">X2H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9698.00000</column>
        <column name="spud_date">2007-01-01 00:00:00.000</column>
        <column name="comp_date">2007-03-10 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">991.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49796</column>
        <column name="bh_longitude">-97.60624</column>
    </row>
    <row>
        <column name="PID">42251312840000</column>
        <column name="LATITUDE">32.49101</column>
        <column name="LONGITUDE">-97.60325</column>
        <column name="NAME">LITTLE HOSS X3H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">X3H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9720.00000</column>
        <column name="spud_date">2006-12-17 00:00:00.000</column>
        <column name="comp_date">2007-03-09 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">991.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49799</column>
        <column name="bh_longitude">-97.60454</column>
    </row>
    <row>
        <column name="PID">42251312850000</column>
        <column name="LATITUDE">32.49099</column>
        <column name="LONGITUDE">-97.60315000000001</column>
        <column name="NAME">LITTLE HOSS X4H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">X4H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10059.00000</column>
        <column name="spud_date">2006-11-29 00:00:00.000</column>
        <column name="comp_date">2008-05-18 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">991.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.49807</column>
        <column name="bh_longitude">-97.60272</column>
    </row>
    <row>
        <column name="PID">42251313980000</column>
        <column name="LATITUDE">32.46419</column>
        <column name="LONGITUDE">-97.58862</column>
        <column name="NAME">LITTLE HOSS N5H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">N5H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9454.00000</column>
        <column name="spud_date">2007-01-10 00:00:00.000</column>
        <column name="comp_date">2007-04-20 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">973.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.47082</column>
        <column name="bh_longitude">-97.59049</column>
    </row>
    <row>
        <column name="PID">42251313990000</column>
        <column name="LATITUDE">32.46414</column>
        <column name="LONGITUDE">-97.58870000000002</column>
        <column name="NAME">LITTLE HOSS N3H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">N3H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10379.00000</column>
        <column name="spud_date">2007-02-13 00:00:00.000</column>
        <column name="comp_date">2007-04-21 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">973.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.47343</column>
        <column name="bh_longitude">-97.59538</column>
    </row>
    <row>
        <column name="PID">42251314040000</column>
        <column name="LATITUDE">32.46416</column>
        <column name="LONGITUDE">-97.58866</column>
        <column name="NAME">LITTLE HOSS N4H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">N4H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">10738.00000</column>
        <column name="spud_date">2007-01-27 00:00:00.000</column>
        <column name="comp_date">2007-02-12 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">973.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.47390</column>
        <column name="bh_longitude">-97.59410</column>
    </row>
    <row>
        <column name="PID">42251314210000</column>
        <column name="LATITUDE">32.48933999999999</column>
        <column name="LONGITUDE">-97.59541</column>
        <column name="NAME">LITTLE HOSS Y4H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">Y4H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9411.00000</column>
        <column name="spud_date">2007-01-24 00:00:00.000</column>
        <column name="comp_date">2007-04-27 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1004.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48245</column>
        <column name="bh_longitude">-97.59062</column>
    </row>
    <row>
        <column name="PID">42251314220000</column>
        <column name="LATITUDE">32.48933999999999</column>
        <column name="LONGITUDE">-97.59546</column>
        <column name="NAME">LITTLE HOSS Y5H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">Y5H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9462.00000</column>
        <column name="spud_date">2007-02-08 00:00:00.000</column>
        <column name="comp_date">2007-04-27 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1004.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48281</column>
        <column name="bh_longitude">-97.59289</column>
    </row>
    <row>
        <column name="PID">42251314230000</column>
        <column name="LATITUDE">32.48933999999999</column>
        <column name="LONGITUDE">-97.59551</column>
        <column name="NAME">LITTLE HOSS Y6H</column>
        <column name="Well_Name">LITTLE HOSS</column>
        <column name="well_number">Y6H</column>
        <column name="operator">GGX</column>
        <column name="status">GAS</column>
        <column name="final_td">9348.00000</column>
        <column name="spud_date">2007-02-24 00:00:00.000</column>
        <column name="comp_date">2007-04-27 00:00:00.000</column>
        <column name="lease_name" null="true"></column>
        <column name="elev">1005.00000</column>
        <column name="plugback_depth" null="true"></column>
        <column name="bh_latitude">32.48295</column>
        <column name="bh_longitude">-97.59501</column>
    </row>