<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultset [
    <!ELEMENT resultset (resultsetdata) >
    <!ELEMENT resultsetdata (row)* >
    <!ELEMENT row (column)+ >
    <!ELEMENT column (#PCDATA)>
    <!ATTLIST column
        null (true | false) "false"
        name CDATA #IMPLIED
    >
]>
<resultset>
    <row>
        <column name="Well ID">42221311570000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">V1H</column>
        <column name="Latitude">32.496120</column>
        <column name="Longitude">-97.621910</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221311580000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">V2H</column>
        <column name="Latitude">32.496600</column>
        <column name="Longitude">-97.620580</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221311580009</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">V2P</column>
        <column name="Latitude">32.489420</column>
        <column name="Longitude">-97.618620</column>
        <column name="Wells" null="true"></column>
        <column name="Wells with recompletions">1</column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221311590000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">V3H</column>
        <column name="Latitude">32.497290</column>
        <column name="Longitude">-97.619280</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221312450000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">P1H</column>
        <column name="Latitude">32.486460</column>
        <column name="Longitude">-97.621820</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221312460000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">P2H</column>
        <column name="Latitude">32.489120</column>
        <column name="Longitude">-97.621030</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221312470000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">erfg</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">P3H</column>
        <column name="Latitude">32.486460</column>
        <column name="Longitude">-97.618750</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221313040000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">D6H</column>
        <column name="Latitude">32.502650</column>
        <column name="Longitude">-97.619630</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221313050000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">D5H</column>
        <column name="Latitude">32.502680</column>
        <column name="Longitude">-97.617740</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221313770000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">A2H</column>
        <column name="Latitude">32.498120</column>
        <column name="Longitude">-97.631660</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221313780000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">A4H</column>
        <column name="Latitude">32.498120</column>
        <column name="Longitude">-97.628290</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221314730000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">F2H</column>
        <column name="Latitude">32.451630</column>
        <column name="Longitude">-97.611490</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221314740000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">F4H</column>
        <column name="Latitude">32.451820</column>
        <column name="Longitude">-97.607440</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42221316750000</column>
        <column name="State">TEXAS</column>
        <column name="County">HOOD</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">D7H</column>
        <column name="Latitude">32.519530</column>
        <column name="Longitude">-97.622120</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251311140000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">J6H</column>
        <column name="Latitude">32.456400</column>
        <column name="Longitude">-97.574510</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251311140009</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">J6P</column>
        <column name="Latitude">32.464190</column>
        <column name="Longitude">-97.575890</column>
        <column name="Wells" null="true"></column>
        <column name="Wells with recompletions">1</column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251311170000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">J8H</column>
        <column name="Latitude">32.455320</column>
        <column name="Longitude">-97.577070</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251311180000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">J7H</column>
        <column name="Latitude">32.455200</column>
        <column name="Longitude">-97.575590</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312110000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">I2H</column>
        <column name="Latitude">32.462020</column>
        <column name="Longitude">-97.589440</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312120000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">I3H</column>
        <column name="Latitude">32.463470</column>
        <column name="Longitude">-97.588180</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312130000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">I4H</column>
        <column name="Latitude">32.463730</column>
        <column name="Longitude">-97.586540</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312720000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">Z3H</column>
        <column name="Latitude">32.482420</column>
        <column name="Longitude">-97.578220</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312730000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">Z2H</column>
        <column name="Latitude">32.482400</column>
        <column name="Longitude">-97.576150</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312740000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">Z1H</column>
        <column name="Latitude">32.482560</column>
        <column name="Longitude">-97.574270</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312830000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">X2H</column>
        <column name="Latitude">32.497960</column>
        <column name="Longitude">-97.606240</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312840000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">X3H</column>
        <column name="Latitude">32.497990</column>
        <column name="Longitude">-97.604540</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251312850000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">X4H</column>
        <column name="Latitude">32.498070</column>
        <column name="Longitude">-97.602720</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251313980000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">N5H</column>
        <column name="Latitude">32.470820</column>
        <column name="Longitude">-97.590490</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251313990000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">N3H</column>
        <column name="Latitude">32.473430</column>
        <column name="Longitude">-97.595380</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314040000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">N4H</column>
        <column name="Latitude">32.473900</column>
        <column name="Longitude">-97.594100</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314210000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">Y4H</column>
        <column name="Latitude">32.482450</column>
        <column name="Longitude">-97.590620</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314220000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">Y5H</column>
        <column name="Latitude">32.482810</column>
        <column name="Longitude">-97.592890</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314230000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS</column>
        <column name="Well Number">Y6H</column>
        <column name="Latitude">32.482950</column>
        <column name="Longitude">-97.595010</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314500000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 3</column>
        <column name="Well Number">L4H</column>
        <column name="Latitude">32.481680</column>
        <column name="Longitude">-97.611670</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314510000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 3</column>
        <column name="Well Number">L2H</column>
        <column name="Latitude">32.473300</column>
        <column name="Longitude">-97.612160</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251314980000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">E1H</column>
        <column name="Latitude">32.455190</column>
        <column name="Longitude">-97.619780</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251315070000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">E2H</column>
        <column name="Latitude">32.457650</column>
        <column name="Longitude">-97.619890</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251315090000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">E4H</column>
        <column name="Latitude">32.443850</column>
        <column name="Longitude">-97.611260</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251315090009</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">E4P</column>
        <column name="Latitude">32.450970</column>
        <column name="Longitude">-97.616660</column>
        <column name="Wells" null="true"></column>
        <column name="Wells with recompletions">1</column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251315140000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">E3H</column>
        <column name="Latitude">32.443820</column>
        <column name="Longitude">-97.609180</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251316310000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">G8H</column>
        <column name="Latitude">32.447710</column>
        <column name="Longitude">-97.598740</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251316330000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">G10H</column>
        <column name="Latitude">32.447040</column>
        <column name="Longitude">-97.601980</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251317550000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">G1H</column>
        <column name="Latitude">32.462410</column>
        <column name="Longitude">-97.610940</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251317560000</column>
        <column name="State">TEXAS</column>
        <column name="County">JOHNSON</column>
        <column name="Operator">GGX</column>
        <column name="Location">TWP:       - Range:      - Sec.    </column>
        <column name="Well Name">LITTLE HOSS 7</column>
        <column name="Well Number">G3H</column>
        <column name="Latitude">32.462450</column>
        <column name="Longitude">-97.606660</column>
        <column name="Wells">1</column>
        <column name="Wells with recompletions" null="true"></column>
        <column name="Wells with sidetracks" null="true"></column>
    </row>
    <row>
        <column name="Well ID">42251318990000</column>
        <column name="State">TEXAS</column>